"""Add boot screen fields to SiteSettings

Revision ID: e172de6e5d19
Revises: bbad52d17b7c
Create Date: 2025-11-14 14:58:10.432580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e172de6e5d19'
down_revision = 'bbad52d17b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boot_screen_line1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('boot_screen_line2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('boot_screen_copyright', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('boot_screen_copyright')
        batch_op.drop_column('boot_screen_line2')
        batch_op.drop_column('boot_screen_line1')

    # ### end Alembic commands ###
